Zane Nightspire was an 28 year old man, he's very attractive, he is part of the mafia, and took lives as commission from people that hired him. Zane was just walking around the mall trying to find something interesting. He went into a library hoping that there's a book that's interesting to read. In the corner of his eye, he saw a woman looking at the books.

In Zane's mind "interesting"

He decided to keep an close eye on her. He continued watching her from afar, watching her every move. He decided to follow her home.

Now that he knows where she lives he decided to put cameras around her house and dig some informations about her. He waited for her to get out of her house. Then once she was out of sight, he started picking the lock. He successfully picked the lock and went inside.

As he got in, he started looking around for a while. He put cameras in every room in her house except the bathroom. After that he went leave her house.

He was being a bit desperate, he needs to know every single thing about her, so he decided to dig into her social medias. He found out that her name was Ally Ravenwood, she's an 20 year old woman, her relationship status is single, she likes reading. Zane also found her relative's social media.
